---
driver:
  name: vagrant
  vm_hostname: riverice.local
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.21.31
  environments_path: 'test/environments'
  client_rb:
    environment: riverflood

platforms:
  - name: centos-7

verifier:
  name: inspec 

suites:
  - name: default
    run_list:
      - recipe[riverice::default]
    verifier:
      inspec_tests:
        - test/smoke/default
        - test/integration/ldm
    attributes:
      riverice:
        user: 'vagrant'
      firewall:
        allow_ssh: true
#        fetch_cron_action: 'delete'
#        partner_networks:
#          - 192.168.1.0/24
