---
driver:
  name: vagrant
  vm_hostname: riverice.local
  customize:
    memory: 4096

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[riverice::default]
    attributes:
      riverice:
        user: 'vagrant'
        fetch_cron_action: 'delete'
