name             'riverice'
maintainer       'UAFGINA'
maintainer_email 'scott@gina.alaska.edu'
license          'All rights reserved'
description      'Installs/Configures riverice algorithms'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.8.1'

chef_version '>= 12.6'

depends 'gina-server'
depends 'poise-python'
depends 'build-essential'
depends 'yum', '~> 3.0'
depends 'yum-epel'
depends 'yum-puias'
depends 'sudo'
depends 'nfs'
depends 'idl'
depends 'ldm'
depends 'gina_firewall'
